### ISSUE TITLE
Python version issues?

### ISSUE THREAD

**Issue by alyaaawad** [h3abionet/h3agwas#12]
I'm running the pipeline on Ubuntu 14.04 machine, with python 3.4 (locally installed dependencies). The behavior with python seems odd though. Kindly see below:

Line [92](https://github.com/h3abionet/h3agwas/blob/3fa7e36bd73d8b9fbc48e6570634fa989bc2b311/templates/drawPCA.py#L92) in `templates/drawPCA.py` produces the error

```
Command error:
    File ".command.sh", line 91
      draw(*evecs,labels,the_colours)
                 ^
  SyntaxError: only named arguments may follow *expression

```

A dirty fix is to change that line such it reads:

```
draw(*(evecs+(labels,the_colours)))

```

With that fix, the pipeline continues until a similar problem occurs from the script  `batchReport.py`  line [503](https://github.com/h3abionet/h3agwas/blob/3fa7e36bd73d8b9fbc48e6570634fa989bc2b311/templates/batchReport.py#L503).

```
Command error:
    output = TAB.join(map(str, [*i,bfrm.loc[i][args.batch_col],"%5.3f"%row['F_MISS'],pfrm.loc[i]]))+                 TAB+TAB.join(map(xstr,sxAnalysis.loc[i]))+EOL
                                       ^
SyntaxError: can use starred expression only as assignment target

```

Reading around, the advice is to solve this problem by using python 3.5, but in the later case the error  reads:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users_current/amelbadawi/training_data/h3agwas/work/36/ebc4dbc425b2eb3db495983cda14a5/.command.sh", line 588, in <module>
    text = text + detailedSexAnalysis(pfrm,ifrm,args.sx_pickle,args.pheno_col,bfrm)
  File "/home/users_current/amelbadawi/training_data/h3agwas/work/36/ebc4dbc425b2eb3db495983cda14a5/.command.sh", line 517, in detailedSexAnalysis
    dumpMissingSexTable(sex_fname,ifrm,sxAnalysis,pfrm[pheno_col],bfrm)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'all'

```

Would you kindly advice?

Thank you,
Alyaa

**Comment by codemeleon** [comment]
Hi,

I would suggest split evecs in to variable instead of using pointer

in file (https://github.com/h3abionet/h3agwas/blob/3fa7e36bd73d8b9fbc48e6570634fa989bc2b311/templates/drawPCA.py)

pc1, pc2, evecs = getEigens() # Line 91

draw(pc1, pc2, evecs,labels,the_colours) # Lijne 92

I hope it will help

--
Regards,
Anmol

**Comment by shaze** [comment]
Apologies all, the documentation was out of date. The requirement is for Python 3.6.

Python 3.6 is widely available and indeed earlier versions are only being  maintained for security fixes

**Comment by alyaaawad** [comment]
We will try install python3.6, thanks for your quick response .
could you please modify the documentation and list scipy as a required
package?!
Thank you

**Comment by shaze** [comment]
This issue has been quiet for a long time so am closing
