### ISSUE TITLE
Why does plink-qc.nf check for samplesheet, sample.phe, and idatpat?  

### ISSUE THREAD

**Issue by mchimenti** [h3abionet/h3agwas#16]
Hello, I'm trying to run plink-qc.nf on my Linux HPC cluster with: 

nextflow run -c my_nf.config /Users/mchiment/.nextflow/assets/h3abionet/h3agwas/plink-qc.nf -profile sgeSingularity --samplesheet "0" --idatpat ""

Where "sgeSingularity" is: 
sgeSingularity {

	process.executor = "sge"
	singularity.autoMounts = true
	singularity.enabled = true
	process.queue = queue

    }

I keep getting errors like this: 

N E X T F L O W  ~  version 19.01.0
Launching `/Users/mchiment/.nextflow/assets/h3abionet/h3agwas/plink-qc.nf` [agitated_lavoisier] - revision: 418f49aacb
Check idatpat=true  ************** is it a valid parameter -- are you using one rather than two - signs or vice-versa
ERROR ~ Argument of `file` function cannot be empty

 -- Check script 'plink-qc.nf' at line: 237 or see '.nextflow.log' file for more details

Line 237: 

sample_sheet_ch = file(params.samplesheet)

***************
Why is it checking for a samplesheet when the directions say we *only* need a BIM/BED/FAM file as input for this pipeline?  

Similarly, if the pipeline also requires a "sample.phe" file, you should put that in the instructions.  I had to create this by hand.

**Comment by mchimenti** [comment]
OK, I seem to have gotten the pipeline to at least kick off with: 
nextflow run /Users/mchiment/.nextflow/assets/h3abionet/h3agwas/plink-qc.nf -profile sgeSingularity --input_pat "willour_041919_bed" --samplesheet "./input/samplesheet.csv"

Where there is a pseudo-phenotype file I created called "sample.phe" under the "input" directory (where the BED/BIM/FAM files are).  It looks like this: 

IID    PHE
235-17-002    0
235-17-004    0
235-17-005    0
235-17-008    0
235-17-009    0
235-17-010    0
235-17-011    0
235-17-012    0
235-17-014    0
235-17-015    0
235-17-016    0
235-17-017    0
etc....

AND there is a pseudo-samplesheet.csv that I also had to create, it looks like this: 
Institute Sample Label,    Manifest Sex, Batch Comment
235-17-002,0,0
235-17-004,0,0
235-17-005,0,0
235-17-008,0,0
235-17-009,0,0
235-17-010,0,0
235-17-011,0,0
235-17-012,0,0
235-17-014,0,0
235-17-015,0,0
235-17-016,0,0
235-17-017,0,0
235-17-020,0,0
.....

********
So now the pipeline starts, and then fails on compPCA with this: 

N E X T F L O W  ~  version 19.01.0
Launching `/Users/mchiment/.nextflow/assets/h3abionet/h3agwas/plink-qc.nf` [silly_hopper] - revision: 418f49aacb
Institute Sample Label
    Manifest Sex
 Batch Comment
WARN: Access to undefined parameter `idatpat` -- Initialise it to a default value eg. `params.idatpat = some_value`
Sexinfo available command
[warm up] executor > sge
WARN: Output `set` must define at least two component -- Check process `compPCA`
Pulling Singularity image docker://quay.io/h3abionet_org/py3plink [cache /Users/mchiment/.singularity/quay.io-h3abionet_org-py3plink.img]
[b3/6994b5] Submitted process > getDuplicateMarkers (1)
[8a/e420a9] Submitted process > sampleSheet
[0e/862028] Submitted process > inMD5 (1)
[d5/e3a627] Submitted process > removeDuplicateSNPs (1)
[50/e06403] Submitted process > getInitMAF (1)
[31/58fbc3] Submitted process > identifyIndivDiscSexinfo (1)
[09/90c9f1] Submitted process > generateIndivMissingnessPlot (1)
[06/2aff3c] Submitted process > getX (1)
[3d/3d37c6] Submitted process > removeQCPhase1 (1)
[41/aad570] Submitted process > generateSnpMissingnessPlot (1)
[9a/ce5202] Submitted process > showInitMAF (1)
[1a/c430c1] Submitted process > showHWEStats (1)
ERROR ~ Error executing process > 'compPCA (1)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  qsub -terse .command.run
Command exit status:
  1

Command output:
  Unable to run job: "job" denied: use parallel environments instead of requesting slots explicitly
  Exiting.

Work dir:
  /Users/mchiment/nf_h3agwas/work/f8/89e74e040f2acbb1ed53ae90b0b58d

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (2)
*********
### How do I get compPCA to run? Do I change max_plink_cores to 1 in the nextflow.config?  

### Also, do my "pseudo" PHE and SAMPLESHEET files have the right format?  

Thanks, Michael

**Comment by shaze** [comment]
Dear Michael

You've asked several questions, not sure what you've sorted out, so I'll try to deal with them in order

First, my apologies. We made some changes late Thursday to add some error checking code and managed add some bugs. I've fixed and committed the changes, so please pull the latest version. I apologise for wasting your time on this. 

1. The first error you reported, the one with "idatpat", was our fault and is fixed. It should be "idpat" (and you only need to specify if you are using a samplesheet)
2. You do not need to provide a `samplesheet`. This is an advanced feature. The default value is "0" and you do not need to specify this.  My bug fix should have made your problem go away. (As an aside the value of using the samplesheet is if your samplesheet contains per-sample call rate and GenCall 10 scores and you are using those for QC. If not, there's no point in using it).
3.  With respect to phenotypes for QC: what is compulsory is a case/control value for which you expect _no_ difference at *genome-wide* level (even though there may be some SNPs which do differ). This could be a genuine case/control value or something you use as a marker to check that there are no  differences between groups. For example, you could use the sex column of a fam file -- one strategy would be just to copy the fam file and put a header row in. Note that the IDs have to be given in PLINK-style, with FID and IID columns. You only seem to have the IID column. I know in many cases the IID will be unique but there are cases that our pipeline has to cope with where they're not and it's hard to distinguish.  To recap, what's compulsory is to define `params.case_control` which is a file name (with header lines) and `params.case_control_col` which the column name.
4. To directly answer your question : your samplesheet value looks good though without call rate and GC10 score it won't be helpful. I would suggest not setting that value. The phenotype file needs a FID column. My suggestion -- make a copy of the fam file and add a header row.
5. There are more advanced features which are optional of doing batch analysis of different sorts and require defining `params.phenotype` and `params.batch` (and the corresponding `col` columns). For example, in our study which is a multi-site study and each site sent their DNA in four different batches we wanted to check genome-wide differences at a site level and at a batch level.  It also helps track down problems that might have occured in a particular shipment. Typically the `batch`, `phenotype` an d `case_control` file would all be the same file, but this need not be the case.
6. The final problem you report `Unable to run job: "job" denied: use parallel environments instead of requesting slots explicitly` is not specific to us but about how you need to run  Nextflow under SGE. I have not done this, but I think it's well documented here `https://gitter.im/nextflow-io/nextflow/archives/2015/12/28` and in the link to the Nextflow documentation.

Here is a very simple example config file, where ``batch4-mod.phe` is the fam file with a header tow and a column header "CC" in the sixth column

```
params.input_dir = "./"
params.input_pat = "batch4"
params.output = "b4-qc"
params.output_dir = "qc"

params.case_control_col="CC"
params.case_control="batch4-mod.phe"
```

Please let us know if this helps or if you have any other problems. and we'd appreciate any other feedback you have

**Comment by mchimenti** [comment]
Dear Scott,

Thank you for your detailed and timely reply and for supporting this pipeline.  I have made some progress but I am still running into issues at the "batch_proc.py" step. 

I did a fresh pull (as of today 5/28/19) of the pipeline.  I am running with: 

nextflow run /Users/mchiment/.nextflow/assets/h3abionet/h3agwas/plink-qc.nf -profile sgeSingularity

In the nextflow.config I specified: 

    case_control         = "${params.input_dir}/sample.phe"
    case_control_col     = "PHENO"

> head ./input/sample.phe
FID IID PID MID SEX PHENO
1 235-17-005 0 0 2 1
2 235-17-043 0 0 1 1
3 235-17-501 0 0 2 0
4 235-17-002 0 0 2 1
5 235-17-526 0 0 2 0
6 235-17-045 0 0 1 1
7 235-17-012 0 0 2 1
8 NIMH_Control_B_009 0 0 0 0
9 235-17-008 0 0 1 1

*********Launching nextflow gives: 

N E X T F L O W  ~  version 19.01.0
Launching `/Users/mchiment/.nextflow/assets/h3abionet/h3agwas/plink-qc.nf` [crazy_albattani] - revision: 3ee82ddf72
WARN: Access to undefined parameter `samplesheet` -- Initialise it to a default value eg. `params.samplesheet = some_value`
The file is called <null> ******
0
Sexinfo available command
[warm up] executor > sge
WARN: Output `set` must define at least two component -- Check process `compPCA`
[7a/bd7122] Submitted process > inMD5 (1)
[41/a1520e] Submitted process > sampleSheet
[de/550568] Submitted process > getDuplicateMarkers (1)
[10/dc628a] Submitted process > removeDuplicateSNPs (1)
[ed/dd3f38] Submitted process > getInitMAF (1)
[2e/47eade] Submitted process > removeQCPhase1 (1)
[f5/a54594] Submitted process > getX (1)
[5c/62de14] Submitted process > identifyIndivDiscSexinfo (1)
[cc/c5df10] Submitted process > generateIndivMissingnessPlot (1)
[97/0d084e] Submitted process > generateSnpMissingnessPlot (1)
[b7/089a58] Submitted process > compPCA (1)
[1a/d652b4] Submitted process > calculateSampleHeterozygosity (1)
[4e/5d019e] Submitted process > showInitMAF (1)
[b0/07e6a7] Submitted process > pruneForIBD (1)
[d3/974e8a] Submitted process > analyseX (1)
[f3/89194b] Submitted process > showHWEStats (1)
[3b/64a0ec] Submitted process > getBadIndivsMissingHet (1)
[a7/615aa4] Submitted process > generateMissHetPlot (1)
[96/d19e71] Submitted process > findRelatedIndiv (1)
[47/a182be] Submitted process > drawPCA (1)
[68/bf88ca] Submitted process > removeQCIndivs (1)
[f8/d1d7ce] Submitted process > batchProc (1)
Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
      return self._engine.get_loc(key)
    File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'FID'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File ".command.sh", line 614, in <module>
      figs = plotPCs(base,eigs,pfrm,args.pheno_col,bfrm,args.batch_col)
    File ".command.sh", line 237, in plotPCs
      df=df.merge(batch,on=['FID','IID'],how='inner')
    File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 5370, in merge
      copy=copy, indicator=indicator, validate=validate)
    File "/usr/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 57, in merge
      validate=validate)
    File "/usr/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 565, in __init__
      self.join_names) = self._get_merge_keys()
    File "/usr/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 824, in _get_merge_keys
      right_keys.append(right[rk]._values)
    File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
      return self._getitem_column(key)
    File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
      return self._get_item_cache(key)
    File "/usr/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
      values = self._data.get(item)
    File "/usr/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
      loc = self.items.get_loc(item)
    File "/usr/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
      return self._engine.get_loc(self._maybe_cast_indexer(key))
    File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'FID'

Work dir:
  /Users/mchiment/nf_h3agwas/work/f8/d1d7ce1317369bc218bae701257dbb

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

******************

**Comment by shaze** [comment]
Could I see the nextflow.config file please?

Scott

**Comment by mchimenti** [comment]
mchiment@argon-login-2: h3agwas$ cat nextflow.config


py3Image = "quay.io/h3abionet_org/py3plink"
gemmaImage="quay.io/h3abionet_org/h3agwas-gemma"
latexImage="quay.io/h3abionet_org/h3agwas-texlive"
swarmPort = '2376'
queue = 'IIHG'

manifest {
    homePage = 'http://github.com/h3abionet/h3agwas'
    description = 'GWAS Pipeline for H3Africa'
    mainScript = 'plink-qc.nf'
}


aws {
    accessKey =''
    secretKey =''
    region    ='eu-west-1'
}

cloud {
    imageId = "ami-710b9108"      // specify your AMI id here
    instanceType = "m4.xlarge"
    subnetId = "null"
    sharedStorageId   = "null"
    sharedStorageMount = "/mnt/shared"
    bootStorageSize = "20GB"     // Size of disk for images spawned
    //   instanceStorageMount = ""   // Set a common mount point for images
    //   instanceStorageDevice = ""  // Set a common block device for images
    autoscale {
        enabled = true
        maxInstances = 1
        terminateWhenIdle = true
    }

}


params {

    // Directories
    work_dir                = "/$PWD"
    input_dir               = "${params.work_dir}/input"
    output_dir              = "${params.work_dir}/output"
    scripts                 = "${params.work_dir}/scripts"
    output                  = "out"


    max_forks            = 95
    // Data
    input_pat            = "willour_041919_bed"


    high_ld_regions_fname = ""
    sexinfo_available    = true
    cut_het_high         = 0.343
    cut_het_low           = 0.15
    cut_diff_miss         = "0.05"
    cut_maf                = "0.01"
    cut_mind              = "0.02"
    cut_geno              = 0.01
    cut_hwe               = 0.008
    pi_hat                = 0.11
    super_pi_hat 	  = 0.7
    f_lo_male             = 0.8 // default for F-sex check -- >= means male
    f_hi_female           = 0.2 //  <= means female
    gc10                 = 0.4  // 10% Gen Call confidence -- 0.4 is very low
    case_control         = "${params.input_dir}/sample.phe"
    case_control_col     = "PHENO"


    phenotype = 0
    pheno_col = "all"
    batch = 0
    batch_col = 0

    samplesize           = 0  // How many individuals in each genotype report 0=ALL
    strandreport         =""
    manifest             =  ""
    idpat                =  0  // or "(\\w+)-DNA_(\\w+)_.*" or ".*_(.*)"


    // Needed for topbottom.nf -- uncomment and put in details
    // reference        = ""
    // output_align     = ""
    // samplesheet      = ""
    // chipdescription  = ""

    accessKey            = ""
    secretKey            = ""
    region               = "eu-west-1"
    AMI                  = "ami-710b9108"
    instanceType         = "m4.xlarge"
    bootStorageSize      = "20GB"
    maxInstances         = "1"

    plink_mem_req        = "750MB"
    other_mem_req        = "750MB"
    big_time             = '12h'
    sharedStorageMount   = "/mnt/shared"
    max_plink_cores      = 4


}
profiles {

    // For execution on a local machine, no containerization. -- Default
    standard {
        process.executor = 'local'
    }
slurm {
process.executor = 'slurm'
process.queue = queue
}



    // Execute pipeline with Docker locally
    docker {
        process.executor = 'local'
        docker.remove      = true
        docker.runOptions  = '--rm'
        docker.registry    = 'quay.io'
        docker.enabled     = true
        docker.temp        = 'auto'
        docker.fixOwnership= true
        docker.process.executor = 'local'
    }


    // Execute pipeline with Docker Swarm setup
    dockerSwarm {
        docker.remove      = true
        docker.runOptions  = '--rm'
        docker.registry    = 'quay.io'
        docker.enabled     = true
        docker.temp        = 'auto'
        docker.fixOwnership= true
        docker.process.executor = 'local'
        docker.engineOptions = "-H :$swarmPort"
    }

    // For execution on a PBS scheduler, no containerization.
    pbs {
        process.executor = 'pbs'
        process.queue = queue
    }


    // For execution on a PBS scheduler with containerization.
    pbsDocker {

        process.executor = 'pbs'
        docker.remove      = true
        docker.runOptions  = '--rm'
        docker.registry    = 'quay.io'
        docker.enabled     = true
        docker.temp        = 'auto'
        docker.fixOwnership= true
    }


    // For execution on a SLURM scheduler, no containerization.
    slurm {
        process.executor = 'slurm'
        process.queue = queue
    }


    // For execution on a PBS scheduler with containerisation.
    slurmDocker {
        process.executor = 'slurm'
        docker.remove      = true
        docker.runOptions  = '--rm'
        docker.registry    = 'quay.io'
        docker.enabled     = true
        docker.temp        = 'auto'
        docker.fixOwnership= true
    }


    singularity.cacheDir = "${HOME}/.singularity"

    singularity {
        singularity.autoMounts = true
        singularity.enabled = true
        process.executor = 'local'
     }

    // For execution on a SLURM scheduler with singularity
    slurmSingularity {

        process.executor = 'slurm'
        singularity.autoMounts = true
        singularity.enabled = true
        process.queue = queue

    }

sgeSingularity {

	process.executor = "sge"
	singularity.autoMounts = true
	singularity.enabled = true
	process.queue = queue
	penv = "smp"

    }
    slurmDocker {
        process.executor = 'slurm'
        process.queue = queue
        docker.remove      = true
        docker.runOptions  = '--rm'
        docker.registry    = 'quay.io'
        docker.enabled     = true
        docker.temp        = 'auto'
        docker.fixOwnership= true

    }

}




process {
    container = py3Image

    withLabel:bigMem {
      memory = '8GB'
    }

    withLabel: gemma {
          container = gemmaImage
    }

}

timeline {
    enabled=true
    file = "nextflow_reports/timeline.html"
}

report {
    enabled = true
    file = "nextflow_reports/report.html"
}

**Comment by shaze** [comment]
Very odd, will have to look at it tomorrow.

What’s odd about this is that as far as I can see,  params.batch = 0, in the nextflow.config file. This being the case the code that crashes should not be called. 

Will try to recreate the problem. What OS are you running?

Scott

**Comment by shaze** [comment]
Could you please email me the file  `/Users/mchiment/nf_h3agwas/work/f8/d1d7ce1317369bc218bae701257dbb/.command.sh`  scott.hazelhurst@wits.ac.za

**Comment by mchimenti** [comment]
> Very odd, will have to look at it tomorrow.
> 
> What’s odd about this is that as far as I can see, params.batch = 0, in the nextflow.config file. This being the case the code that crashes should not be called.
> 
> Will try to recreate the problem. What OS are you running?
> 
> Scott

This is what I thought too.  You said batch analysis was off by default, and I did not change that parameter in the config file.

**Comment by shaze** [comment]
Michael,

As reported privately I was able to reproduce the problem which is due to differences in the way different versions  of pandas handles certain operations. I have now made changes that should make the scripts robust to the version of pandas and have tested on pandas 22  (which I was able to reproduce the problem) and pandas 24. I have pushed through changes. Please try now.

**Comment by mchimenti** [comment]
Hi Scott, thank you I will test it now.  Just a suggestion, but you could simply pull a docker/singularity container with python/pandas in it and use that to run your custom scripts.  That way you'd always have control over pandas versions.

**Comment by shaze** [comment]
Thanks for the suggestion

We do have these containers and I should be doing regression testing against these to make sure I am always backwards compatible.

We don't have complete control because some of the environments we are designing for do not suppot docker/singularity and so users will install their own versions. We can't check against everythiing of course, but ideall what I shoud be doing is in my own environment testing against latest releases of software and then always doing regression testing against our own docker images, which is what I had failed to do.

**Comment by mchimenti** [comment]
Hi Scott, 
So the pipeline does now run past the batch proc step.  There is a new error: 

ERROR ~ Error executing process > 'calculateSnpSkewStatus (1)'

Caused by:
  Missing output file(s) `willour_041919_bed-nd-c-c.missing` expected by process `calculateSnpSkewStatus (1)`

Command executed:

  cp sample.phe cc.phe
  plink --threads 4 --autosome --bfile willour_041919_bed-nd-c-c  --pheno cc.phe --pheno-name PHENO --test-missing mperm=10000 --hardy --out willour_041919_bed-nd-c-c
  if ! [ -e willour_041919_bed-nd-c-c.missing.mperm ]; then
     echo " CHR                               SNP         EMP1         EMP2 " > willour_041919_bed-nd-c-c.missing.mperm
  fi

Command exit status:
  0

Command output:
  PLINK v1.90b5.2 64-bit (9 Jan 2018)            www.cog-genomics.org/plink/1.9/
  (C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
  Logging to willour_041919_bed-nd-c-c.log.
  Options in effect:
    --autosome
    --bfile willour_041919_bed-nd-c-c
    --hardy
    --out willour_041919_bed-nd-c-c
    --pheno cc.phe
    --pheno-name PHENO
    --test-missing mperm=10000
    --threads 4

  257523 MB RAM detected; reserving 128761 MB for main workspace.
  281985 variants loaded from .bim file.
  44 people (13 males, 31 females) loaded from .fam.
  27 phenotype values present after --pheno.
  Using up to 4 threads (change this with --threads).
  Before main variant filters, 44 founders and 0 nonfounders present.
  Calculating allele frequencies... done.
  --hardy: Writing Hardy-Weinberg report (founders only) to
  willour_041919_bed-nd-c-c.hwe ... done.
  281985 variants and 44 people pass filters and QC.
  Among remaining phenotypes, 0 are cases and 27 are controls.  (17 phenotypes
  are missing.)

The pipeline is assigning all of the "case" phenotypes to missing, which is causing this step to fail.

**Comment by mchimenti** [comment]
mchiment@argon-login-2: output$ head willour_041919_bed-nd-c.fam
1 235-17-005 0 0 2 1
2 235-17-043 0 0 1 1
3 235-17-501 0 0 2 -9
4 235-17-002 0 0 2 1
5 235-17-526 0 0 2 -9
6 235-17-045 0 0 1 1
7 235-17-012 0 0 2 1
8 NIMH_Control_B_009 0 0 0 -9
9 235-17-008 0 0 1 1
10 235-17-523 0 0 2 -9

********
Actually, it looks like all of the controls are being assigned as missing.  I'm not sure I understand what's going on here. 

There are supposed to be 27 cases and 17 controls, + 4 internal controls.

**Comment by mchimenti** [comment]
Here is cc.phe from nf_h3agwas/work/46/efa0c2bfa91d7cab51875a96f0af31 which is just sample.phe copied from the inputs.  

This is correct.  So now this is confusing, why is PLINK getting confused and thinking that cases are controls and controls are missing?  

>> cat cc.phe
FID IID PID MID SEX PHENO
1 235-17-005 0 0 2 1
2 235-17-043 0 0 1 1
3 235-17-501 0 0 2 0
4 235-17-002 0 0 2 1
5 235-17-526 0 0 2 0
6 235-17-045 0 0 1 1
7 235-17-012 0 0 2 1
8 NIMH_Control_B_009 0 0 0 0
9 235-17-008 0 0 1 1
10 235-17-523 0 0 2 0
11 235-17-011 0 0 2 1
12 235-17-530 0 0 1 0
13 NIMH_Control_A_009 0 0 0 0
14 235-17-503 0 0 2 0
15 235-17-065 0 0 2 1
16 235-17-506 0 0 1 0
17 235-17-063 0 0 2 1
18 235-17-521 0 0 1 0
19 235-17-060 0 0 2 1
20 235-17-009 0 0 2 1
21 235-17-017 0 0 2 1
22 235-17-535 0 0 1 0
23 235-17-058 0 0 2 1
24 235-17-051 0 0 1 1
25 NIMH_Control_A_011 0 0 0 0
26 235-17-508 0 0 1 0
27 235-17-046 0 0 2 1
28 235-17-512 0 0 2 0
29 235-17-015 0 0 1 1
30 235-17-042 0 0 2 1
31 235-17-050 0 0 2 1
32 235-17-520 0 0 2 0
33 NIMH_Control_B_011 0 0 0 0
34 235-17-004 0 0 2 1
35 235-17-047 0 0 2 1
36 235-17-537 0 0 2 0
37 235-17-020 0 0 1 1
38 235-17-525 0 0 1 0
39 235-17-522 0 0 2 0
40 235-17-066 0 0 2 1
41 235-17-511 0 0 2 0
42 235-17-529 0 0 2 0
43 235-17-010 0 0 2 1
44 235-17-040 0 0 2 1
45 235-17-014 0 0 1 1
46 235-17-016 0 0 2 1
47 235-17-536 0 0 2 0
48 235-17-024 0 0 2 1

**Comment by shaze** [comment]
Dear Michael

Gosh, you're giving our pipeline a thorough testing!

Here  the issue is that PLINK uses 1 for cases and 2 for controls. Both 0 and -9 mean missing values.

See https://www.cog-genomics.org/plink/1.9/formats#fam   for more detail.

Of course, our pipeline should fail gracefully, so I wil definitely put this on the list of things to improve 

Regards

Scott

**Comment by mchimenti** [comment]
Hi Scott, 
OK, that is my fault for coding the case/control status with the alternate style.  BUT I seem to have fixed it, at least for this module with this (adding the "--1" flag in the plink command).  With this change (below), the pipeline runs to completion.  

My question now is, are there other processes expecting default coding where I need to add the "--1" flag to indicate alternate coding?  OR, should I recode my FAM and PHE files to be default PLINK style (-9,0,1,2) instead of alt-PLINK (-9,0,1)?  

thanks,

Michael 

script:
   base  = plinks[0].baseName
   out   = base.replace(".","_")
   mperm = "${base}.missing.mperm"
   phe   = plinks[3]
   """
    cp $phe cc.phe
    plink --threads ${max_plink_cores} --autosome --bfile $base $sexinfo $diffpheno **--1** --test-missing mperm=10000 --hardy --out $out
    if ! [ -e $mperm ]; then
       echo "$mperm_header" > $mperm
    fi

   """

*******

**Comment by shaze** [comment]
Dear Michael

For the QC pipeline  there would be no probem, I think. The PC analysis also uses the phenotype value — not so much a technical problem but whether the picture mean anything.

For the association testing pipeline, I think it would be a major issue. It is rather messy this because different tools use different conventions. Which tool do you think you will be using?

I’ve been thinking that the best would be for the pipeline for case/control values to be specified with the text  “case”/“control” and then the pipeline could convert to 1/2 if using PLINK or 0/1 if using Gemma

I’ll think about this a bit more

Scott




> On 30 May 2019, at 10:38 PM, Michael Chimenti <notifications@github.com> wrote:
>
> Hi Scott,
> OK, that is my fault for coding the case/control status wrong. BUT I seem to have fixed it, at least for this module with this (adding the "--1" flag in the plink command). With this change (below), the pipeline runs to completion.
>
> My question now is, are there other modules expecting default coding where I need to add the "--1" flag to indicate alternate coding?
>
> script:
> base = plinks[0].baseName
> out = base.replace(".","_")
> mperm = "${base}.missing.mperm"
> phe = plinks[3]
> """
> cp $phe cc.phe
> plink --threads ${max_plink_cores} --autosome --bfile $base $sexinfo $diffpheno --1 --test-missing mperm=10000 --hardy --out $out
> if ! [ -e $mperm ]; then
> echo "$mperm_header" > $mperm
> fi
>
> """
>
> I guess my question now is, is
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

This communication is intended for the addressee only. It is confidential. If you have received this communication in error, please notify us immediately and destroy the original message. You may not copy or disseminate this communication without the permission of the University. Only authorised signatories are competent to enter into agreements on behalf of the University and recipients are thus advised that the content of this message may not be legally binding on the University and may contain the personal views and opinions of the author, which are not necessarily the views and opinions of The University of the Witwatersrand, Johannesburg. All agreements between the University and outsiders are subject to South African Law unless the University agrees in writing to the contrary.
